# Generated by Django 3.2.9 on 2021-12-14 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sign',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('spassword', models.CharField(max_length=15)),
            ],
        ),
    ]
