# Generated by Django 3.2.9 on 2021-12-15 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_sign_sbz'),
    ]

    operations = [
        migrations.CreateModel(
            name='rooms',
            fields=[
                ('rno', models.AutoField(primary_key=True, serialize=False)),
                ('rtype', models.CharField(max_length=10)),
                ('rprice', models.IntegerField()),
                ('rin', models.BooleanField()),
            ],
        ),
    ]
