# Generated by Django 3.2.9 on 2021-12-21 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_rooms'),
    ]

    operations = [
        migrations.CreateModel(
            name='bookrecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bdate', models.DateTimeField()),
                ('btype', models.IntegerField()),
                ('bno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.rooms')),
            ],
        ),
    ]
