# Generated by Django 3.2.9 on 2021-12-21 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_bookrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookrecord',
            name='bcno',
            field=models.ForeignKey(default=110, on_delete=django.db.models.deletion.CASCADE, to='web.sign'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookrecord',
            name='iscancel',
            field=models.IntegerField(default=0),
        ),
    ]
