# Generated by Django 3.2.9 on 2021-12-21 15:08

from django.db import migrations, models
import django.utils.timezone as timezone

class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20211221_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookrecord',
            name='bend',
            field=models.DateTimeField(default=timezone.now),
            preserve_default=False,
        ),
    ]
