# Generated by Django 3.2.9 on 2021-12-21 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_bookrecord_bend'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookrecord',
            name='bend',
        ),
    ]
