# Generated by Django 3.2.9 on 2021-12-21 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_remove_bookrecord_bend'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookrecord',
            name='bdays',
            field=models.IntegerField(default=1),
        ),
    ]
