# Generated by Django 3.2.9 on 2021-12-21 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_bookrecord_bdays'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookrecord',
            name='bno',
        ),
    ]
