# Generated by Django 3.2.9 on 2021-12-22 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_bookrecord_broomtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='checkedrecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crno', models.IntegerField()),
                ('cdate', models.DateTimeField()),
                ('ccno', models.IntegerField()),
                ('cdays', models.IntegerField(default=1)),
                ('cpaid', models.IntegerField(default=0)),
            ],
        ),
    ]
