# Generated by Django 3.2.9 on 2021-12-22 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_checkedrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='moneyrecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mtype', models.IntegerField()),
                ('mrno', models.IntegerField()),
                ('money', models.IntegerField()),
                ('mdate', models.DateTimeField()),
                ('mdays', models.IntegerField()),
            ],
        ),
    ]
