# Generated by Django 3.2.9 on 2021-12-22 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_moneyrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='moneyrecord',
            name='mrtype',
            field=models.CharField(default=-1, max_length=10),
            preserve_default=False,
        ),
    ]
